// This file is auto-generated by prepare_images.bat. Do not edit by hand.
export interface GeneratedImage { title: string; imageUrl: string; miniatureUrl?: string }
export const GENERATED_IMAGE_DATA: { [folder: string]: GeneratedImage[] } = {
    "photos/category4":  [
                             {
                                 "title":  "Bru Ko E Syst",
                                 "miniatureUrl":  "assets/images/photos/category4/miniatures/bru_ko_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category4/bru_ko_e_syst_1.webp"
                             },
                             {
                                 "title":  "Lili A Bru Ko",
                                 "miniatureUrl":  "assets/images/photos/category4/miniatures/lili_a_bru_ko_1.webp",
                                 "imageUrl":  "assets/images/photos/category4/lili_a_bru_ko_1.webp"
                             },
                             {
                                 "title":  "Majka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category4/miniatures/majka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category4/majka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Masky E Syste",
                                 "miniatureUrl":  "assets/images/photos/category4/miniatures/masky_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category4/masky_0_syste_1.webp"
                             },
                             {
                                 "title":  "Rados E Syste",
                                 "miniatureUrl":  "assets/images/photos/category4/miniatures/rados_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category4/rados_0_syste_1.webp"
                             },
                             {
                                 "title":  "Sa Ka A Bra K",
                                 "miniatureUrl":  "assets/images/photos/category4/miniatures/sa_ka_a_bra_k_1.webp",
                                 "imageUrl":  "assets/images/photos/category4/sa_ka_a_bra_k_1.webp"
                             },
                             {
                                 "title":  "Tehu C System",
                                 "miniatureUrl":  "assets/images/photos/category4/miniatures/tehu_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category4/tehu_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Tomo C System",
                                 "miniatureUrl":  "assets/images/photos/category4/miniatures/tomo_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category4/tomo_c_0_syst_1.webp"
                             }
                         ],
    "paintings":  [
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/11_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/11_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/12_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/12_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/13_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/13_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/14_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/14_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/15_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/15_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/16_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/16_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/17_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/17_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/18_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/18_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "Co System Col",
                          "miniatureUrl":  "assets/images/paintings/miniatures/1_0_co_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/1_0_co_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/21_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/21_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/22_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/22_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/23_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/23_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/24_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/24_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/25_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/25_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/26_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/26_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/27_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/27_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/28_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/28_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/29_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/29_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "Co System Col",
                          "miniatureUrl":  "assets/images/paintings/miniatures/2_0_co_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/2_0_co_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/30_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/30_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/31_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/31_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/32_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/32_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/33_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/33_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/34_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/34_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/35_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/35_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/36_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/36_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/37_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/37_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/38_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/38_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/39_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/39_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "Co System Col",
                          "miniatureUrl":  "assets/images/paintings/miniatures/3_0_co_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/3_0_co_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/40_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/40_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/41_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/41_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/42_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/42_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/43_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/43_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/44_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/44_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/45_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/45_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/46_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/46_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/47_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/47_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/48_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/48_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "Co System Col",
                          "miniatureUrl":  "assets/images/paintings/miniatures/4_0_co_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/4_0_co_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/50_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/50_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/51_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/51_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/52_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/52_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/53_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/53_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/54_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/54_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/55_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/55_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "C System Coll",
                          "miniatureUrl":  "assets/images/paintings/miniatures/56_0_c_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/56_0_c_0_syst_1.webp"
                      },
                      {
                          "title":  "Co System Col",
                          "miniatureUrl":  "assets/images/paintings/miniatures/5_0_co_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/5_0_co_0_syst_1.webp"
                      },
                      {
                          "title":  "Co System Col",
                          "miniatureUrl":  "assets/images/paintings/miniatures/8_0_co_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/8_0_co_0_syst_1.webp"
                      },
                      {
                          "title":  "Co System Col",
                          "miniatureUrl":  "assets/images/paintings/miniatures/9_0_co_0_syst_1.webp",
                          "imageUrl":  "assets/images/paintings/9_0_co_0_syst_1.webp"
                      }
                  ],
    "Root":  [
                 {
                     "title":  "Background He",
                     "miniatureUrl":  "assets/images/background_he_1.jpg",
                     "imageUrl":  "assets/images/background_he_1.jpg"
                 },
                 {
                     "title":  "Logo Cb E Sys",
                     "miniatureUrl":  "assets/images/logo_cb_e_sys_1.png",
                     "imageUrl":  "assets/images/logo_cb_e_sys_1.png"
                 },
                 {
                     "title":  "Seamless Canv",
                     "miniatureUrl":  "assets/images/seamless_canv_1.jpg",
                     "imageUrl":  "assets/images/seamless_canv_1.jpg"
                 },
                 {
                     "title":  "Seamless Cosm",
                     "miniatureUrl":  "assets/images/seamless_cosm_1.jpg",
                     "imageUrl":  "assets/images/seamless_cosm_1.jpg"
                 }
             ],
    "profile_images":  [
                           {
                               "title":  "473 System Co",
                               "miniatureUrl":  "assets/images/profile_images/miniatures/473321091_136_1.webp",
                               "imageUrl":  "assets/images/profile_images/473321091_136_1.webp"
                           },
                           {
                               "title":  "Dance E Syste",
                               "miniatureUrl":  "assets/images/profile_images/miniatures/dance_0_e_sy_1.webp",
                               "imageUrl":  "assets/images/profile_images/dance_0_e_sy_1.webp"
                           },
                           {
                               "title":  "Dsc Pp S Syst",
                               "miniatureUrl":  "assets/images/profile_images/miniatures/DSC_6858_pp_S_1.webp",
                               "imageUrl":  "assets/images/profile_images/DSC_6858_pp_S_1.webp"
                           },
                           {
                               "title":  "Greeting Syst",
                               "miniatureUrl":  "assets/images/profile_images/miniatures/greeting_0_Sy_1.webp",
                               "imageUrl":  "assets/images/profile_images/greeting_0_Sy_1.webp"
                           },
                           {
                               "title":  "Leaning On Wa",
                               "miniatureUrl":  "assets/images/profile_images/miniatures/leaning_on_wa_1.webp",
                               "imageUrl":  "assets/images/profile_images/leaning_on_wa_1.webp"
                           },
                           {
                               "title":  "Wak System Co",
                               "miniatureUrl":  "assets/images/profile_images/miniatures/wak04242_1_0_1.webp",
                               "imageUrl":  "assets/images/profile_images/wak04242_1_0_1.webp"
                           },
                           {
                               "title":  "Wak System Co",
                               "miniatureUrl":  "assets/images/profile_images/miniatures/WAK05690_0_Sy_1.webp",
                               "imageUrl":  "assets/images/profile_images/WAK05690_0_Sy_1.webp"
                           }
                       ],
    "photos/category2":  [
                             {
                                 "title":  "Adamko E Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/adamko_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/adamko_e_syst_1.webp"
                             },
                             {
                                 "title":  "Adam C System",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/adam_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/adam_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Anjel E Syste",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/anjel_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/anjel_0_syste_1.webp"
                             },
                             {
                                 "title":  "Babo C System",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/babo_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/babo_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "B Mimi E Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/b_mimi_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/b_mimi_e_syst_1.webp"
                             },
                             {
                                 "title":  "Dianka E Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/dianka_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/dianka_e_syst_1.webp"
                             },
                             {
                                 "title":  "Didi C System",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/didi_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/didi_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Diev Atko Sys",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/diev_atko_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/diev_atko_Sys_1.webp"
                             },
                             {
                                 "title":  "Drobec E Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/drobec_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/drobec_e_syst_1.webp"
                             },
                             {
                                 "title":  "Dvoji Ky Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/dvoji_ky_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/dvoji_ky_sys_1.webp"
                             },
                             {
                                 "title":  "Ela Co System",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/ela_co_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/ela_co_0_syst_1.webp"
                             },
                             {
                                 "title":  "Emka C System",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/emka_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/emka_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Filipko E Sys",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/filipko_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/filipko_e_sy_1.webp"
                             },
                             {
                                 "title":  "Jakubko E Sys",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/jakubko_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/jakubko_e_sy_1.webp"
                             },
                             {
                                 "title":  "Kajka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/kajka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/kajka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Karolina Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/karolina_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/karolina_sys_1.webp"
                             },
                             {
                                 "title":  "Karol Nka Sys",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/karol_nka_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/karol_nka_Sys_1.webp"
                             },
                             {
                                 "title":  "Kol E System",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/kol_2_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/kol_2_0_syste_1.webp"
                             },
                             {
                                 "title":  "Kristianko Sy",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/kristianko_Sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/kristianko_Sy_1.webp"
                             },
                             {
                                 "title":  "Lujzi Ka Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/lujzi_ka_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/lujzi_ka_sys_1.webp"
                             },
                             {
                                 "title":  "Macko E Syste",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/macko_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/macko_0_syste_1.webp"
                             },
                             {
                                 "title":  "Matiasko Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/matiasko_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/matiasko_sys_1.webp"
                             },
                             {
                                 "title":  "Ninka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/ninka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/ninka_0_syste_1.webp"
                             },
                             {
                                 "title":  "No Ulky E Sys",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/no_ulky_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/no_ulky_e_sy_1.webp"
                             },
                             {
                                 "title":  "Ove Ka E Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/ove_ka_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/ove_ka_e_syst_1.webp"
                             },
                             {
                                 "title":  "Pusinka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/pusinka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/pusinka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Smev C System",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/smev_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/smev_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Snehulienka S",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/snehulienka_S_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/snehulienka_S_1.webp"
                             },
                             {
                                 "title":  "Srdie Ko Syst",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/srdie_ko_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/srdie_ko_sys_1.webp"
                             },
                             {
                                 "title":  "Tamka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/tamka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/tamka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Timko E Syste",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/timko_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/timko_0_syste_1.webp"
                             },
                             {
                                 "title":  "Valentinka Sy",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/VAlentinka_Sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/VAlentinka_Sy_1.webp"
                             },
                             {
                                 "title":  "Val Co System",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/val_co_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/val_co_0_syst_1.webp"
                             },
                             {
                                 "title":  "Vlasana E Sys",
                                 "miniatureUrl":  "assets/images/photos/category2/miniatures/vlasana_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category2/vlasana_e_sy_1.webp"
                             }
                         ],
    "candles":  [
                    {
                        "title":  "20 System Col",
                        "miniatureUrl":  "assets/images/candles/miniatures/20250408_2042_1.webp",
                        "imageUrl":  "assets/images/candles/20250408_2042_1.webp"
                    },
                    {
                        "title":  "496 System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/496190477_147_1.webp",
                        "imageUrl":  "assets/images/candles/496190477_147_1.webp"
                    },
                    {
                        "title":  "496 System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/496296698_147_1.webp",
                        "imageUrl":  "assets/images/candles/496296698_147_1.webp"
                    },
                    {
                        "title":  "496 System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/496767503_147_1.webp",
                        "imageUrl":  "assets/images/candles/496767503_147_1.webp"
                    },
                    {
                        "title":  "Dsc K System",
                        "miniatureUrl":  "assets/images/candles/miniatures/dsc_9151_k_0_1.webp",
                        "imageUrl":  "assets/images/candles/dsc_9151_k_0_1.webp"
                    },
                    {
                        "title":  "Dsc System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/DSC_9156_0_Sy_1.webp",
                        "imageUrl":  "assets/images/candles/DSC_9156_0_Sy_1.webp"
                    },
                    {
                        "title":  "Dsc System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/DSC_9161_0_Sy_1.webp",
                        "imageUrl":  "assets/images/candles/DSC_9161_0_Sy_1.webp"
                    },
                    {
                        "title":  "Dsc System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/DSC_9164_0_Sy_1.webp",
                        "imageUrl":  "assets/images/candles/DSC_9164_0_Sy_1.webp"
                    },
                    {
                        "title":  "Dsc System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/DSC_9184_0_Sy_1.webp",
                        "imageUrl":  "assets/images/candles/DSC_9184_0_Sy_1.webp"
                    },
                    {
                        "title":  "Dsc System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/DSC_9186_0_Sy_1.webp",
                        "imageUrl":  "assets/images/candles/DSC_9186_0_Sy_1.webp"
                    },
                    {
                        "title":  "Dsf System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/DSF5963_0_Sys_1.webp",
                        "imageUrl":  "assets/images/candles/DSF5963_0_Sys_1.webp"
                    },
                    {
                        "title":  "Dsf System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/DSF5964_0_Sys_1.webp",
                        "imageUrl":  "assets/images/candles/DSF5964_0_Sys_1.webp"
                    },
                    {
                        "title":  "Dsf System Co",
                        "miniatureUrl":  "assets/images/candles/miniatures/DSF6002_0_Sys_1.webp",
                        "imageUrl":  "assets/images/candles/DSF6002_0_Sys_1.webp"
                    },
                    {
                        "title":  "Obr Uvodna Dy",
                        "miniatureUrl":  "assets/images/candles/miniatures/obr_uvodna_dy_1.webp",
                        "imageUrl":  "assets/images/candles/obr_uvodna_dy_1.webp"
                    }
                ],
    "photos/category1":  [
                             {
                                 "title":  "Agatka E Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/agatka_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/agatka_e_syst_1.webp"
                             },
                             {
                                 "title":  "Alica E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/alica_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/alica_0_syste_1.webp"
                             },
                             {
                                 "title":  "Berenikafareb",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/berenikafareb_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/berenikafareb_1.webp"
                             },
                             {
                                 "title":  "Brachovia Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/brachovia_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/brachovia_Sys_1.webp"
                             },
                             {
                                 "title":  "Bra Kovia Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/bra_kovia_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/bra_kovia_Sys_1.webp"
                             },
                             {
                                 "title":  "Damian E Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/damian_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/damian_e_syst_1.webp"
                             },
                             {
                                 "title":  "Dorka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/dorka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/dorka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Emka A Ma Ko",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/emka_a_ma_ko_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/emka_a_ma_ko_1.webp"
                             },
                             {
                                 "title":  "Evi Ka E Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/evi_ka_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/evi_ka_e_syst_1.webp"
                             },
                             {
                                 "title":  "Evka C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/evka_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/evka_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Fb Mi Ka Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/fb_mi_ka_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/fb_mi_ka_sys_1.webp"
                             },
                             {
                                 "title":  "Fifo A Didi S",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/fifo_a_didi_S_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/fifo_a_didi_S_1.webp"
                             },
                             {
                                 "title":  "Filipko E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/filipko_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/filipko_e_sy_1.webp"
                             },
                             {
                                 "title":  "Filip E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/filip_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/filip_0_syste_1.webp"
                             },
                             {
                                 "title":  "Fiot C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/fiot_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/fiot_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Frajer E Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/frajer_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/frajer_e_syst_1.webp"
                             },
                             {
                                 "title":  "Gabika E Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/gabika_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/gabika_e_syst_1.webp"
                             },
                             {
                                 "title":  "Gerda E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/gerda_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/gerda_0_syste_1.webp"
                             },
                             {
                                 "title":  "Gloria E Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/gloria_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/gloria_e_syst_1.webp"
                             },
                             {
                                 "title":  "Hugo C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/hugo_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/hugo_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Ivka C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/ivka_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/ivka_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Kajka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/kajka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/kajka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Klobuk E Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/klobuk_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/klobuk_e_syst_1.webp"
                             },
                             {
                                 "title":  "Kola C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/kola_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/kola_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Kola Ik E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/kola_ik_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/kola_ik_e_sy_1.webp"
                             },
                             {
                                 "title":  "Kor Ule E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/kor_ule_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/kor_ule_e_sy_1.webp"
                             },
                             {
                                 "title":  "Laso Ka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/laso_ka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/laso_ka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Laura E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/laura_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/laura_0_syste_1.webp"
                             },
                             {
                                 "title":  "Laurika E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/laurika_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/laurika_e_sy_1.webp"
                             },
                             {
                                 "title":  "Liankanadhern",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/liankanadhern_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/liankanadhern_1.webp"
                             },
                             {
                                 "title":  "Lilinka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/lilinka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/lilinka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Lili C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/lili_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/lili_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Lili Fifo Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/LILI_FIFO_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/LILI_FIFO_Sys_1.webp"
                             },
                             {
                                 "title":  "Lilkazlata Sy",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/lilkazlata_Sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/lilkazlata_Sy_1.webp"
                             },
                             {
                                 "title":  "Lilka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/lilka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/lilka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Lucinka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/lucinka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/lucinka_e_sy_1.webp"
                             },
                             {
                                 "title":  "L L System Co",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/l_l_0_system_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/l_l_0_system_1.webp"
                             },
                             {
                                 "title":  "Ma I Ka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/ma_i_ka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/ma_i_ka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Melania E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/melania_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/melania_e_sy_1.webp"
                             },
                             {
                                 "title":  "Michalka Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/michalka_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/michalka_sys_1.webp"
                             },
                             {
                                 "title":  "Mi Ka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/mi_ka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/mi_ka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Mi Ka Fb Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/mi_ka_fb_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/mi_ka_fb_sys_1.webp"
                             },
                             {
                                 "title":  "Modelka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/modelka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/modelka_e_sy_1.webp"
                             },
                             {
                                 "title":  "M M Co System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/m_m_co_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/m_m_co_0_syst_1.webp"
                             },
                             {
                                 "title":  "Neli E System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/neli_1_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/neli_1_e_syst_1.webp"
                             },
                             {
                                 "title":  "Neli C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/neli_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/neli_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Nikolasko Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/nikolasko_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/nikolasko_Sys_1.webp"
                             },
                             {
                                 "title":  "Nikolas E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/nikolas_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/nikolas_e_sy_1.webp"
                             },
                             {
                                 "title":  "Ninka Fb Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/ninka_fb_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/ninka_fb_sys_1.webp"
                             },
                             {
                                 "title":  "Oliterez Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/oliterez_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/oliterez_sys_1.webp"
                             },
                             {
                                 "title":  "Pusinka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/pusinka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/pusinka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Sane C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/sane_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/sane_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Sara C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/sara_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/sara_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Sestri Ky S S",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/sestri_ky_1_S_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/sestri_ky_1_S_1.webp"
                             },
                             {
                                 "title":  "Sestri Ky Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/sestri_ky_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/sestri_ky_Sys_1.webp"
                             },
                             {
                                 "title":  "Slnie Ko Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/slnie_ko_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/slnie_ko_sys_1.webp"
                             },
                             {
                                 "title":  "Sofinka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/sofinka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/sofinka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Sofi C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/sofi_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/sofi_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Steline Ka Sy",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/steline_ka_Sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/steline_ka_Sy_1.webp"
                             },
                             {
                                 "title":  "Stelka E Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/stelka_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/stelka_e_syst_1.webp"
                             },
                             {
                                 "title":  "S Psikom Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/s_psikom_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/s_psikom_sys_1.webp"
                             },
                             {
                                 "title":  "S S Co System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/s_s_co_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/s_s_co_0_syst_1.webp"
                             },
                             {
                                 "title":  "Terezka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/terezka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/terezka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Tete E System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/tete_1_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/tete_1_e_syst_1.webp"
                             },
                             {
                                 "title":  "Tete C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/tete_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/tete_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "T L System Co",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/t_l_0_system_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/t_l_0_system_1.webp"
                             },
                             {
                                 "title":  "Vanes E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/vanes_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/vanes_0_syste_1.webp"
                             },
                             {
                                 "title":  "Viktoria Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/viktoria_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/viktoria_sys_1.webp"
                             },
                             {
                                 "title":  "Vvikinka Syst",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/vvikinka_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/vvikinka_sys_1.webp"
                             },
                             {
                                 "title":  "Zoe Co System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/zoe_co_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/zoe_co_0_syst_1.webp"
                             },
                             {
                                 "title":  "Zora C System",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/zora_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/zora_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Zorka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category1/miniatures/zorka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category1/zorka_0_syste_1.webp"
                             }
                         ],
    "photos/category3":  [
                             {
                                 "title":  "37 System Col",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/37313554_2014_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/37313554_2014_1.webp"
                             },
                             {
                                 "title":  "Bordo E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/bordo_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/bordo_0_syste_1.webp"
                             },
                             {
                                 "title":  "Danka A Janko",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/danka_a_janko_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/danka_a_janko_1.webp"
                             },
                             {
                                 "title":  "Diev Ata Syst",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/diev_ata_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/diev_ata_sys_1.webp"
                             },
                             {
                                 "title":  "Divo Ienka Sy",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/DIVO_IENKA_Sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/DIVO_IENKA_Sy_1.webp"
                             },
                             {
                                 "title":  "Echovci E Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/echovci_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/echovci_e_sy_1.webp"
                             },
                             {
                                 "title":  "Echovky E Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/echovky_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/echovky_e_sy_1.webp"
                             },
                             {
                                 "title":  "Fb C System C",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/fb_0_c_system_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/fb_0_c_system_1.webp"
                             },
                             {
                                 "title":  "Jankasmi Kom",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/jankasmi_kom_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/jankasmi_kom_1.webp"
                             },
                             {
                                 "title":  "Jankasocinom",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/jankasocinom_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/jankasocinom_1.webp"
                             },
                             {
                                 "title":  "Janka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/janka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/janka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Jona C System",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/jona_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/jona_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Juli C System",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/juli_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/juli_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Julka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/julka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/julka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Kamo Ky E Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/kamo_ky_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/kamo_ky_e_sy_1.webp"
                             },
                             {
                                 "title":  "Khala E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/khala_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/khala_0_syste_1.webp"
                             },
                             {
                                 "title":  "Ko Iarik Syst",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/ko_iarik_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/ko_iarik_sys_1.webp"
                             },
                             {
                                 "title":  "Kroje E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/kroje_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/kroje_0_syste_1.webp"
                             },
                             {
                                 "title":  "Lilinka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/lilinka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/lilinka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Lilismaminkou",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/lilismaminkou_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/lilismaminkou_1.webp"
                             },
                             {
                                 "title":  "Lili E System",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/lili_1_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/lili_1_e_syst_1.webp"
                             },
                             {
                                 "title":  "Lili C System",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/lili_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/lili_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Martinka Syst",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/martinka_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/martinka_sys_1.webp"
                             },
                             {
                                 "title":  "Masarovci Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/masarovci_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/masarovci_Sys_1.webp"
                             },
                             {
                                 "title":  "Mati C System",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/mati_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/mati_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Matko E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/matko2_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/matko2_e_syst_1.webp"
                             },
                             {
                                 "title":  "Ma Ko E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/ma_ko_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/ma_ko_0_syste_1.webp"
                             },
                             {
                                 "title":  "Mi Ko E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/mi_ko_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/mi_ko_0_syste_1.webp"
                             },
                             {
                                 "title":  "Neli C System",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/neli_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/neli_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Neli Ervena S",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/neli_ervena_S_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/neli_ervena_S_1.webp"
                             },
                             {
                                 "title":  "Robin E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/robin_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/robin_0_syste_1.webp"
                             },
                             {
                                 "title":  "Sofi C System",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/sofi_c_0_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/sofi_c_0_syst_1.webp"
                             },
                             {
                                 "title":  "Stelisjulkou",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/stelisjulkou_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/stelisjulkou_1.webp"
                             },
                             {
                                 "title":  "Steliuvody Sy",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/steliuvody_Sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/steliuvody_Sy_1.webp"
                             },
                             {
                                 "title":  "Stelivoda Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/stelivoda_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/stelivoda_Sys_1.webp"
                             },
                             {
                                 "title":  "Steli E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/steli_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/steli_0_syste_1.webp"
                             },
                             {
                                 "title":  "Steli S Zsts",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/steli_s_zsts_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/steli_s_zsts_1.webp"
                             },
                             {
                                 "title":  "Steli Zapad S",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/STELI_ZAPAD_S_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/STELI_ZAPAD_S_1.webp"
                             },
                             {
                                 "title":  "Stelkazrkadlo",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/stelkazrkadlo_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/stelkazrkadlo_1.webp"
                             },
                             {
                                 "title":  "Stelka E Syst",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/stelka_e_syst_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/stelka_e_syst_1.webp"
                             },
                             {
                                 "title":  "Terezka E Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/terezka_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/terezka_e_sy_1.webp"
                             },
                             {
                                 "title":  "Terez E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/terez_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/terez_0_syste_1.webp"
                             },
                             {
                                 "title":  "Timi Domi Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/timi_domi_Sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/timi_domi_Sys_1.webp"
                             },
                             {
                                 "title":  "Toma Oko Syst",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/toma_oko_sys_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/toma_oko_sys_1.webp"
                             },
                             {
                                 "title":  "Vaneska E Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/vaneska_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/vaneska_e_sy_1.webp"
                             },
                             {
                                 "title":  "V Zdoba E Sys",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/v_zdoba_e_sy_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/v_zdoba_e_sy_1.webp"
                             },
                             {
                                 "title":  "Xenka A Tomky",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/xenka_a_tomky_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/xenka_a_tomky_1.webp"
                             },
                             {
                                 "title":  "Zuzka E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/zuzka_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/zuzka_0_syste_1.webp"
                             },
                             {
                                 "title":  "Zuzka A Ani K",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/Zuzka_a_Ani_k_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/Zuzka_a_Ani_k_1.webp"
                             },
                             {
                                 "title":  "Z Pad E Syste",
                                 "miniatureUrl":  "assets/images/photos/category3/miniatures/z_pad_0_syste_1.webp",
                                 "imageUrl":  "assets/images/photos/category3/z_pad_0_syste_1.webp"
                             }
                         ]
};
