export enum T {
  aboutMe_anchor = 'O me', // tlacitko na presun na stranku O me
  services_anchor = 'Sluzby', // tlacitko na presun na stranku Sluzby
  contact_anchor = 'Kontakt', // tlacitko na presun na stranku Kontakt
  services_header = 'Čo ponúkam', // nadpis na strance sluzby
  about_me_intro = 'Volám sa Janka Zemianek, moje umelecké meno je Joly. Som tvorivá duša, ktorá vníma krásu v momentoch a detailoch. Tvorenie je pre mňa prirodzený spôsob vyjadrenia a porozumenia svetu okolo mňa. Verím v tvorbu, ktorá má hlbší význam. Každé dielo vzniká s rešpektom k človeku, pre ktorého je určené. Tvorenie je pre mňa spôsob, ako sa dotknúť emócií, ktoré sa nedajú pomenovať slovami, ale len precítiť. V každom obraze, fotografii a plameni sviečky hľadám rovnováhu medzi jemnosťou a hĺbkou, medzi tým, čo je viditeľné a tým, čo ostáva skryté. Tvorím diela, ktoré nie sú len dekoráciou, ale pozvaním na návrat k sebe a k tomu, čo je podstatné. Tvorím so zámerom a úctou. Tvorím s láskou a verím, že každé dielo má svoju vlastnú dušu, tak ako každý z nás. ✨🤍',
  about_me_title1 = 'Fotografka 📸',
  about_me_part1 = 'Som rodinná fotografka so zameraním na deti. Vo svojej práci sa sústreďujem na prirodzené momenty, emócie a autentické prepojenie medzi rodičmi a deťmi. Mojím cieľom je zachytiť skutočné chvíle, smiech a dotyky, ktoré tvoria jedinečný príbeh každej rodiny. Hľadám okamih, ktorý sa stáva večnosťou v podobe fotografie.',
  about_me_title2 = 'Maliarka 🎨',
  about_me_part2 = 'Popri fotografovaní sa venujem aj maľovaniu obrazov a ručnej výrobe sviečok. Všetko, čo tvorím, vzniká s myšlienkou priniesť do každodenného života viac radosti a lásky. Maľujem energetické obrazy s jasným zámerom a silnou energiou. Každý obraz je pre mňa meditáciou a zároveň cestou, ako preniesť pocity na plátno. Fotografovanie aj maľbu vnímam ako rovnocenné formy vizuálneho rozprávania príbehov, obe vychádzajú z detailu, nálady a autenticity. 🎨🌙',
  about_me_title3 = 'Sviečky 🕯️',
  about_me_part3 = 'Ručná výroba sviečok je pre mňa pomalý a vedomý proces. Každá sviečka vzniká s dôrazom na detail. Každá sviečka vzniká s jasným zámerom priniesť lásku, hojnosť, zdravie alebo pokoj a harmóniu. Sviečky tak prinášajú klientovi to, čo túži posilniť alebo zhmotniť. Pri zapálení sa stáva súčasťou osobného rituálu a vedomého zastavenia sa. 🔥',
  about_me_title4 = 'Tvorba s duší ✨',
  about_me_part4 = 'Tvorenie je pre mňa spôsob, ako sa dotýkať emócií, ktoré sa nedajú pomenovať slovami ale len precítiť. V každom obraze, fotografií a plameni sviečky, hľadám rovnováhu medzi jemnosťou a hĺbkou, medzi tým, čo je viditeľné a tým, čo ostáva skryté.',
  about_me_outro1 = 'Tvorím diela, ktoré nie sú len dekoráciou, ale pozvaním na návrat k sebe a k tomu, čo je podstatné. 🌿',
  about_me_outro2 = 'Tvorím so zámerom a úctou. ✨🤍',
  about_me_outro3 = 'Tvorím s láskou a verím, že každé dielo má svoju vlastnú dušu, tak ako každý z nás. ✨🤍',
  paintings_header = 'Obrazy', // nadpis na strance obrazy
  paintings_subtitle = 'Energetické obrazy s jasným zámerom a jemnou silou.', // podtitul na strance obrazy
  paintings_footer_message = 'Ak vás niektorý obraz osloví, napíšte mi a rada vám poradím.', // text pod fotkami obrazov
  photography_header = 'Fotografia', // nadpis na strance fotky
  photography_subtitle = 'Rodinné fotenie plné prirodzených momentov a emócií.', // podtitul na strance fotky
  photography_category_1 = 'Deti', // nazev fotek kategorie 1
  photography_category1_subtitle = 'Úprimný smiech, iskra v očiach a spontánne chvíle.', // podtitul fotek kategorie 1
  photography_category1_footer_message = 'Zachytím detský svet tak, ako ho cítite – jemne a prirodzene.', // text pod fotkami kategorie 1
  photography_category_2 = 'Bábätká', // nazev kategorie 2
  photography_category2_subtitle = 'Nežné detaily prvých dní a bezpečný, pokojný rytmus.', // podtitul kategorie 2
  photography_category2_footer_message = 'Fotenie bábätiek prebieha pomaly, s dôrazom na pohodlie a blízkosť.', // text pod fotkami kategorie 2
  photography_category_3 = 'Rodina', // nazev kategorie 3
  photography_category3_subtitle = 'Spoločné chvíle, objatia a malé rituály, ktoré tvoria domov.', // podtitul kategorie 3
  photography_category3_footer_message = 'Rodinné fotenie je o vás – o prepojení, ktoré zostane navždy.', // text pod fotkami kategorie 3
  photography_category_4 = 'Čakáme bábätko', // nazev kategorie 4
  photography_category4_subtitle = 'Jemné svetlo, nežnosť a radostné očakávanie.', // podtitul kategorie 4
  photography_category4_footer_message = 'Tehotenské fotenie zachytí silu aj krehkosť tohto jedinečného obdobia.', // text pod fotkami kategorie 4
  candles_header = 'Sviečky', // nadpis na strance sviecky
  candles_subtitle = 'Ručne robené sviečky s láskou a zámerom.', // podtitul na strance sviecky
  candles_footer_message = 'Každá sviečka vzniká ako malý rituál – pre pokoj, hojnosť a harmóniu.', // text pod fotkami sviecok
  write_me = 'Napíš mi', // nadpis na strance Kontakt
  p404_Title = '404', // nadpis 404 stranky
  p404_Message = 'Stránka nenájdená', // text na 404 strance
  go_home = 'Na hlavnú stránku', // text pro tlacitko na 404 strance
  input_name = 'Meno',
  input_name_required = 'Pole "Meno" je povinné.',
  input_name_length = '"Meno" musí mať minimálne 3 znaky.',
  input_email = 'Email',
  input_email_required = 'Pole "Email" je povinné.',
  input_email_invalid = 'Zadajte platný email.',
  input_message = 'Správa',
  input_message_required = 'Pole "Správa" je povinné.',
  button_send = 'Odoslať',
  address_label = 'Adresa',
  address_value = 'Tobias Klima, 12345, Praha 5',
  phone_label = 'Telefón',
  phone_value = '+420 123 456 789',
  email_label = 'Email',
  email_value = 'foteniejeradost@gmail.com',
  expand_image = 'Zväčšiť obrázok',
  value_copied = 'bolo skopírované do pamäte'
}
