name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to the branch from which you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'  # Specify your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: ng build --prod --base-href /<repository-name>/

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: dist/<your-project-name>  # The folder the action should deploy.
